# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wordcloudtool_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 691, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout_Main = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout_Main.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Main.setObjectName("gridLayout_Main")
        self.horizontalLayout_WordsAndStop = QtWidgets.QHBoxLayout()
        self.horizontalLayout_WordsAndStop.setObjectName("horizontalLayout_WordsAndStop")
        self.tabWidgetStopWords = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidgetStopWords.setObjectName("tabWidgetStopWords")
        self.tab_StopWordsFile = QtWidgets.QWidget()
        self.tab_StopWordsFile.setObjectName("tab_StopWordsFile")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_StopWordsFile)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_StopWordsFile = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_StopWordsFile.setObjectName("label_StopWordsFile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_StopWordsFile)
        self.lineEdit_StopWordsFile = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_StopWordsFile.setObjectName("lineEdit_StopWordsFile")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_StopWordsFile)
        self.pushButton_BrowseStopWordsFile = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_BrowseStopWordsFile.setObjectName("pushButton_BrowseStopWordsFile")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_BrowseStopWordsFile)
        self.tabWidgetStopWords.addTab(self.tab_StopWordsFile, "")
        self.tab_StopWordsEditor = QtWidgets.QWidget()
        self.tab_StopWordsEditor.setObjectName("tab_StopWordsEditor")
        self.comboBox = QtWidgets.QComboBox(self.tab_StopWordsEditor)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 201, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_StopWordsEditorChoice = QtWidgets.QLabel(self.tab_StopWordsEditor)
        self.label_StopWordsEditorChoice.setGeometry(QtCore.QRect(20, 0, 201, 17))
        self.label_StopWordsEditorChoice.setObjectName("label_StopWordsEditorChoice")
        self.listViewStopWordsEditor = QtWidgets.QListView(self.tab_StopWordsEditor)
        self.listViewStopWordsEditor.setGeometry(QtCore.QRect(10, 50, 201, 181))
        self.listViewStopWordsEditor.setObjectName("listViewStopWordsEditor")
        self.label_StopWWordsEditorWord = QtWidgets.QLabel(self.tab_StopWordsEditor)
        self.label_StopWWordsEditorWord.setGeometry(QtCore.QRect(223, 90, 111, 20))
        self.label_StopWWordsEditorWord.setObjectName("label_StopWWordsEditorWord")
        self.lineEdit_StopWordsEditorWord = QtWidgets.QLineEdit(self.tab_StopWordsEditor)
        self.lineEdit_StopWordsEditorWord.setGeometry(QtCore.QRect(220, 110, 113, 25))
        self.lineEdit_StopWordsEditorWord.setObjectName("lineEdit_StopWordsEditorWord")
        self.pushButton_StopWordsEditorDelete = QtWidgets.QPushButton(self.tab_StopWordsEditor)
        self.pushButton_StopWordsEditorDelete.setGeometry(QtCore.QRect(226, 140, 101, 25))
        self.pushButton_StopWordsEditorDelete.setObjectName("pushButton_StopWordsEditorDelete")
        self.pushButton_StopWordsEditorAdd = QtWidgets.QPushButton(self.tab_StopWordsEditor)
        self.pushButton_StopWordsEditorAdd.setGeometry(QtCore.QRect(225, 60, 101, 25))
        self.pushButton_StopWordsEditorAdd.setObjectName("pushButton_StopWordsEditorAdd")
        self.tabWidgetStopWords.addTab(self.tab_StopWordsEditor, "")
        self.horizontalLayout_WordsAndStop.addWidget(self.tabWidgetStopWords)
        self.tabWidget_WordCloud = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget_WordCloud.setObjectName("tabWidget_WordCloud")
        self.tab_WordCloud = QtWidgets.QWidget()
        self.tab_WordCloud.setObjectName("tab_WordCloud")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_WordCloud)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 331, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_WordCloud = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_WordCloud.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_WordCloud.setObjectName("verticalLayout_WordCloud")
        self.graphicsViewWordCloud = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        self.graphicsViewWordCloud.setObjectName("graphicsViewWordCloud")
        self.verticalLayout_WordCloud.addWidget(self.graphicsViewWordCloud)
        self.pushButton_WordCloud = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_WordCloud.setObjectName("pushButton_WordCloud")
        self.verticalLayout_WordCloud.addWidget(self.pushButton_WordCloud)
        self.tabWidget_WordCloud.addTab(self.tab_WordCloud, "")
        self.tab_WordHistogram = QtWidgets.QWidget()
        self.tab_WordHistogram.setObjectName("tab_WordHistogram")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_WordHistogram)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 331, 231))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_WordHistogram = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_WordHistogram.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_WordHistogram.setObjectName("verticalLayout_WordHistogram")
        self.graphicsView_WordHistogram = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.graphicsView_WordHistogram.setObjectName("graphicsView_WordHistogram")
        self.verticalLayout_WordHistogram.addWidget(self.graphicsView_WordHistogram)
        self.pushButton_WordHistogram = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_WordHistogram.setObjectName("pushButton_WordHistogram")
        self.verticalLayout_WordHistogram.addWidget(self.pushButton_WordHistogram)
        self.tabWidget_WordCloud.addTab(self.tab_WordHistogram, "")
        self.horizontalLayout_WordsAndStop.addWidget(self.tabWidget_WordCloud)
        self.gridLayout_Main.addLayout(self.horizontalLayout_WordsAndStop, 2, 0, 1, 1)
        self.gridLayout_TextSource = QtWidgets.QGridLayout()
        self.gridLayout_TextSource.setObjectName("gridLayout_TextSource")
        self.labelChooseSource = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelChooseSource.setFont(font)
        self.labelChooseSource.setObjectName("labelChooseSource")
        self.gridLayout_TextSource.addWidget(self.labelChooseSource, 0, 0, 1, 1)
        self.gridLayout_Main.addLayout(self.gridLayout_TextSource, 0, 0, 1, 1)
        self.horizontalLayout_Visualize = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Visualize.setObjectName("horizontalLayout_Visualize")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Visualize.addItem(spacerItem)
        self.pushButton_Visualize = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Visualize.sizePolicy().hasHeightForWidth())
        self.pushButton_Visualize.setSizePolicy(sizePolicy)
        self.pushButton_Visualize.setObjectName("pushButton_Visualize")
        self.horizontalLayout_Visualize.addWidget(self.pushButton_Visualize)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Visualize.addItem(spacerItem1)
        self.gridLayout_Main.addLayout(self.horizontalLayout_Visualize, 3, 0, 1, 1)
        self.gridLayout_SourceTabs = QtWidgets.QGridLayout()
        self.gridLayout_SourceTabs.setObjectName("gridLayout_SourceTabs")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPasteText = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabPasteText.sizePolicy().hasHeightForWidth())
        self.tabPasteText.setSizePolicy(sizePolicy)
        self.tabPasteText.setObjectName("tabPasteText")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabPasteText)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 681, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_PasteText = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_PasteText.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_PasteText.setObjectName("verticalLayout_PasteText")
        self.labelPasteText_Text = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelPasteText_Text.setObjectName("labelPasteText_Text")
        self.verticalLayout_PasteText.addWidget(self.labelPasteText_Text)
        self.labelPasteText_Req = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.labelPasteText_Req.setFont(font)
        self.labelPasteText_Req.setObjectName("labelPasteText_Req")
        self.verticalLayout_PasteText.addWidget(self.labelPasteText_Req)
        self.textEditPasteText = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEditPasteText.setObjectName("textEditPasteText")
        self.verticalLayout_PasteText.addWidget(self.textEditPasteText)
        self.tabWidget.addTab(self.tabPasteText, "")
        self.tabWebPageURL = QtWidgets.QWidget()
        self.tabWebPageURL.setObjectName("tabWebPageURL")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabWebPageURL)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 681, 54))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_WebURL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_WebURL.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_WebURL.setObjectName("horizontalLayout_WebURL")
        self.verticalLayout_WebURL = QtWidgets.QVBoxLayout()
        self.verticalLayout_WebURL.setObjectName("verticalLayout_WebURL")
        self.labelWebPageURL_URL = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelWebPageURL_URL.setObjectName("labelWebPageURL_URL")
        self.verticalLayout_WebURL.addWidget(self.labelWebPageURL_URL)
        self.labelWebPageURL_Ex = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelWebPageURL_Ex.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(8)
        self.labelWebPageURL_Ex.setFont(font)
        self.labelWebPageURL_Ex.setObjectName("labelWebPageURL_Ex")
        self.verticalLayout_WebURL.addWidget(self.labelWebPageURL_Ex)
        self.horizontalLayout_WebURL.addLayout(self.verticalLayout_WebURL)
        self.lineEdit_WebPageURL = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_WebPageURL.setObjectName("lineEdit_WebPageURL")
        self.horizontalLayout_WebURL.addWidget(self.lineEdit_WebPageURL)
        self.tabWidget.addTab(self.tabWebPageURL, "")
        self.tabTextFile = QtWidgets.QWidget()
        self.tabTextFile.setObjectName("tabTextFile")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tabTextFile)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 681, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayoutTextFile = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayoutTextFile.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutTextFile.setObjectName("horizontalLayoutTextFile")
        self.labelTextFile = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelTextFile.setObjectName("labelTextFile")
        self.horizontalLayoutTextFile.addWidget(self.labelTextFile)
        self.lineEditTextFile = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEditTextFile.setObjectName("lineEditTextFile")
        self.horizontalLayoutTextFile.addWidget(self.lineEditTextFile)
        self.pushButtonBrowseTextFile = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButtonBrowseTextFile.setObjectName("pushButtonBrowseTextFile")
        self.horizontalLayoutTextFile.addWidget(self.pushButtonBrowseTextFile)
        self.tabWidget.addTab(self.tabTextFile, "")
        self.tabWordDoc = QtWidgets.QWidget()
        self.tabWordDoc.setObjectName("tabWordDoc")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tabWordDoc)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 681, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayoutTextFile_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayoutTextFile_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutTextFile_2.setObjectName("horizontalLayoutTextFile_2")
        self.labelWordDoc = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.labelWordDoc.setObjectName("labelWordDoc")
        self.horizontalLayoutTextFile_2.addWidget(self.labelWordDoc)
        self.lineEditWordDoc = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEditWordDoc.setObjectName("lineEditWordDoc")
        self.horizontalLayoutTextFile_2.addWidget(self.lineEditWordDoc)
        self.pushButtonBrowseWordDoc = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButtonBrowseWordDoc.setObjectName("pushButtonBrowseWordDoc")
        self.horizontalLayoutTextFile_2.addWidget(self.pushButtonBrowseWordDoc)
        self.tabWidget.addTab(self.tabWordDoc, "")
        self.tabPDFFile = QtWidgets.QWidget()
        self.tabPDFFile.setObjectName("tabPDFFile")
        self.layoutWidget = QtWidgets.QWidget(self.tabPDFFile)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 681, 62))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelPDFFileType = QtWidgets.QLabel(self.layoutWidget)
        self.labelPDFFileType.setObjectName("labelPDFFileType")
        self.horizontalLayout.addWidget(self.labelPDFFileType)
        self.comboBoxPDFFile = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxPDFFile.setObjectName("comboBoxPDFFile")
        self.comboBoxPDFFile.addItem("")
        self.comboBoxPDFFile.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxPDFFile)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.horizontalLayoutTextFile_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTextFile_3.setObjectName("horizontalLayoutTextFile_3")
        self.labelPDFFile = QtWidgets.QLabel(self.layoutWidget)
        self.labelPDFFile.setObjectName("labelPDFFile")
        self.horizontalLayoutTextFile_3.addWidget(self.labelPDFFile)
        self.lineEditPDFFile = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPDFFile.setObjectName("lineEditPDFFile")
        self.horizontalLayoutTextFile_3.addWidget(self.lineEditPDFFile)
        self.pushButtonBrowsePDFFile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonBrowsePDFFile.setObjectName("pushButtonBrowsePDFFile")
        self.horizontalLayoutTextFile_3.addWidget(self.pushButtonBrowsePDFFile)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayoutTextFile_3)
        self.tabWidget.addTab(self.tabPDFFile, "")
        self.tabImageFile = QtWidgets.QWidget()
        self.tabImageFile.setObjectName("tabImageFile")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tabImageFile)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 681, 62))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelImageFileType = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelImageFileType.setObjectName("labelImageFileType")
        self.horizontalLayout_2.addWidget(self.labelImageFileType)
        self.comboBoxImageFile = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBoxImageFile.setObjectName("comboBoxImageFile")
        self.comboBoxImageFile.addItem("")
        self.comboBoxImageFile.addItem("")
        self.comboBoxImageFile.addItem("")
        self.comboBoxImageFile.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxImageFile)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.horizontalLayoutTextFile_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTextFile_4.setObjectName("horizontalLayoutTextFile_4")
        self.labelImageFile = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelImageFile.setObjectName("labelImageFile")
        self.horizontalLayoutTextFile_4.addWidget(self.labelImageFile)
        self.lineEditImageFile = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditImageFile.setObjectName("lineEditImageFile")
        self.horizontalLayoutTextFile_4.addWidget(self.lineEditImageFile)
        self.pushButtonBrowseImageFile = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonBrowseImageFile.setObjectName("pushButtonBrowseImageFile")
        self.horizontalLayoutTextFile_4.addWidget(self.pushButtonBrowseImageFile)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayoutTextFile_4)
        self.tabWidget.addTab(self.tabImageFile, "")
        self.gridLayout_SourceTabs.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_Main.addLayout(self.gridLayout_SourceTabs, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStart_Over = QtWidgets.QAction(MainWindow)
        self.actionStart_Over.setObjectName("actionStart_Over")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionStart_Over)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetStopWords.setCurrentIndex(0)
        self.tabWidget_WordCloud.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxPDFFile.setCurrentIndex(0)
        self.comboBoxImageFile.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WordCloud Tool"))
        self.tabWidgetStopWords.setStatusTip(_translate("MainWindow", "Change the stop words list from the default values"))
        self.label_StopWordsFile.setText(_translate("MainWindow", "Select the file containing your Stop Words:"))
        self.pushButton_BrowseStopWordsFile.setToolTip(_translate("MainWindow", "Select the stop file word list file to use"))
        self.pushButton_BrowseStopWordsFile.setText(_translate("MainWindow", "Browse"))
        self.tabWidgetStopWords.setTabText(self.tabWidgetStopWords.indexOf(self.tab_StopWordsFile), _translate("MainWindow", "Stop Words File"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Alphabetical"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Alphabetical"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Usage"))
        self.label_StopWordsEditorChoice.setText(_translate("MainWindow", "Chose the sorting preference:"))
        self.label_StopWWordsEditorWord.setText(_translate("MainWindow", "Selected word:"))
        self.lineEdit_StopWordsEditorWord.setToolTip(_translate("MainWindow", "Type in the word to add here"))
        self.pushButton_StopWordsEditorDelete.setToolTip(_translate("MainWindow", "Delete the selected word from the stop list"))
        self.pushButton_StopWordsEditorDelete.setText(_translate("MainWindow", "Delete Word"))
        self.pushButton_StopWordsEditorAdd.setToolTip(_translate("MainWindow", "Add the selected word to the stop list"))
        self.pushButton_StopWordsEditorAdd.setText(_translate("MainWindow", "Add Word"))
        self.tabWidgetStopWords.setTabText(self.tabWidgetStopWords.indexOf(self.tab_StopWordsEditor), _translate("MainWindow", "Stop Words Editor"))
        self.tabWidget_WordCloud.setStatusTip(_translate("MainWindow", "View the results of the document analysis"))
        self.pushButton_WordCloud.setToolTip(_translate("MainWindow", "Display the word cloud in a separate larger window"))
        self.pushButton_WordCloud.setText(_translate("MainWindow", "Show WordCloud in Separate Window"))
        self.tabWidget_WordCloud.setTabText(self.tabWidget_WordCloud.indexOf(self.tab_WordCloud), _translate("MainWindow", "Word Cloud"))
        self.pushButton_WordHistogram.setToolTip(_translate("MainWindow", "Display the histogram in a separate larger window"))
        self.pushButton_WordHistogram.setText(_translate("MainWindow", "Show Histogram is Separate Window"))
        self.tabWidget_WordCloud.setTabText(self.tabWidget_WordCloud.indexOf(self.tab_WordHistogram), _translate("MainWindow", "Word Histogram"))
        self.labelChooseSource.setText(_translate("MainWindow", "Choose your text source:"))
        self.pushButton_Visualize.setToolTip(_translate("MainWindow", "Analyze the document and generate the Word Cloud"))
        self.pushButton_Visualize.setText(_translate("MainWindow", "Visualize!"))
        self.tabWidget.setToolTip(_translate("MainWindow", "Select the file to open"))
        self.tabWidget.setStatusTip(_translate("MainWindow", "Choose your text source based on the file type"))
        self.labelPasteText_Text.setText(_translate("MainWindow", "Paste text to be visualized:"))
        self.labelPasteText_Req.setText(_translate("MainWindow", "plain text, 500 kilobyte max"))
        self.textEditPasteText.setToolTip(_translate("MainWindow", "Paste or type in the words to be analyzed here"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPasteText), _translate("MainWindow", "Paste Text"))
        self.labelWebPageURL_URL.setText(_translate("MainWindow", "Web page URL:"))
        self.labelWebPageURL_Ex.setText(_translate("MainWindow", "e.g. http://myblog.com\n"
""))
        self.lineEdit_WebPageURL.setToolTip(_translate("MainWindow", "Paste or type in the URL link here"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWebPageURL), _translate("MainWindow", "Web Page URL"))
        self.labelTextFile.setText(_translate("MainWindow", "Select a File:"))
        self.pushButtonBrowseTextFile.setToolTip(_translate("MainWindow", "Select the text file to open"))
        self.pushButtonBrowseTextFile.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTextFile), _translate("MainWindow", "Text File"))
        self.labelWordDoc.setText(_translate("MainWindow", "Select a File:"))
        self.pushButtonBrowseWordDoc.setToolTip(_translate("MainWindow", "Select the word document to open"))
        self.pushButtonBrowseWordDoc.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWordDoc), _translate("MainWindow", "Word Doc"))
        self.labelPDFFileType.setText(_translate("MainWindow", "PDF File Type:"))
        self.comboBoxPDFFile.setCurrentText(_translate("MainWindow", "Text"))
        self.comboBoxPDFFile.setItemText(0, _translate("MainWindow", "Text"))
        self.comboBoxPDFFile.setItemText(1, _translate("MainWindow", "Image"))
        self.labelPDFFile.setText(_translate("MainWindow", "Select a File:"))
        self.pushButtonBrowsePDFFile.setToolTip(_translate("MainWindow", "Select the PDF file to open"))
        self.pushButtonBrowsePDFFile.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPDFFile), _translate("MainWindow", "PDF File"))
        self.labelImageFileType.setText(_translate("MainWindow", "Image File Type:"))
        self.comboBoxImageFile.setCurrentText(_translate("MainWindow", "PNG"))
        self.comboBoxImageFile.setItemText(0, _translate("MainWindow", "PNG"))
        self.comboBoxImageFile.setItemText(1, _translate("MainWindow", "GIF"))
        self.comboBoxImageFile.setItemText(2, _translate("MainWindow", "JPEG"))
        self.comboBoxImageFile.setItemText(3, _translate("MainWindow", "TIFF"))
        self.labelImageFile.setText(_translate("MainWindow", "Select a File:"))
        self.pushButtonBrowseImageFile.setToolTip(_translate("MainWindow", "Select the Image file to open"))
        self.pushButtonBrowseImageFile.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImageFile), _translate("MainWindow", "Image File"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionStart_Over.setText(_translate("MainWindow", "Start Over"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
